"use client";

import { useEffect, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase/browser";
import { ArrowRight, Check, ChevronRight, Code2, Copy, FileCode2, FolderOpen, Gauge, GitBranch, KeyRound, LockKeyhole, LogOut, MoreHorizontal, Plus, Search, Settings, ShieldCheck, Terminal, Trash2, X, Zap } from "lucide-react";

type ProjectStatus = "Protected" | "Draft" | "Processing";
type Project = { id: string; name: string; description: string; language: string; status: ProjectStatus; source_code?: string; protected_code?: string; updated_at: string; };
type ApiKey = { id: string; name: string; key_prefix: string; last_used_at: string | null; created_at: string; };
type Deployment = { id: string; project_id: string; label: string; endpoint: string | null; status: string; created_at: string; project?: { name: string } | null; };
type Tab = "overview" | "projects" | "obfuscate" | "deployments" | "api" | "settings" | "owner";
const OWNER_EMAIL = "om0801174@gmail.com";
type AuthMode = "login" | "signup";

const tabMeta: Record<Tab, { label: string; icon: typeof Gauge }> = { overview: { label: "Overview", icon: Gauge }, projects: { label: "Projects", icon: FolderOpen }, obfuscate: { label: "Obfuscate", icon: ShieldCheck }, deployments: { label: "Deployments", icon: GitBranch }, api: { label: "API access", icon: KeyRound }, settings: { label: "Settings", icon: Settings }, owner: { label: "Owner", icon: LockKeyhole } };

export default function Home() {
  const [screen, setScreen] = useState<"landing" | "auth" | "dashboard">("landing");
  const [authMode, setAuthMode] = useState<AuthMode>("signup");
  const [tab, setTab] = useState<Tab>("overview");
  const [userLabel, setUserLabel] = useState("new user");
  const [userEmail, setUserEmail] = useState("");
  const [projects, setProjects] = useState<Project[]>([]);
  const [deployments, setDeployments] = useState<Deployment[]>([]);
  const [keys, setKeys] = useState<ApiKey[]>([]);
  const [stats, setStats] = useState({ totalProjects: 0, protectedBuilds: 0, apiRequests: 0, avgProtectionTime: "—" });
  const [toast, setToast] = useState<string | null>(null);
  const [project, setProject] = useState<Project | null>(null);
  const [source, setSource] = useState("");
  const [method, setMethod] = useState("bytestrings,transformnums,minify");
  const [protecting, setProtecting] = useState(false);
  const [newName, setNewName] = useState("");
  const [newDescription, setNewDescription] = useState("");
  const [newSource, setNewSource] = useState("");
  const [newKeyName, setNewKeyName] = useState("");
  const [generatedKey, setGeneratedKey] = useState<string | null>(null);
  const [query, setQuery] = useState("");
  const [deploymentLabel, setDeploymentLabel] = useState("");
  const [deploymentEndpoint, setDeploymentEndpoint] = useState("");
  const [authBusy, setAuthBusy] = useState(false);
  const [modal, setModal] = useState<"new-project" | "new-deployment" | null>(null);

  useEffect(() => {
    const client = getSupabaseBrowserClient();
    if (!client) return;
    void client.auth.getSession().then(({ data }) => { if (data.session) { setScreen("dashboard"); setUserEmail(data.session.user.email ?? ""); setUserLabel(data.session.user.email?.split("@")[0] ?? "new user"); void loadAll(); } });
    const { data: listener } = client.auth.onAuthStateChange((_event, session) => { if (session) { setScreen("dashboard"); setUserEmail(session.user.email ?? ""); setUserLabel(session.user.email?.split("@")[0] ?? "new user"); void loadAll(); } });
    return () => listener.subscription.unsubscribe();
  }, []);

  async function loadAll() {
    const client = getSupabaseBrowserClient();
    if (!client) return;
    const { data: { session } } = await client.auth.getSession();
    if (!session) return;
    const [projectResponse, statsResponse, deploymentResponse, keyResponse] = await Promise.all([fetch("/api/projects"), fetch("/api/stats"), fetch("/api/deployments"), fetch("/api/keys")]);
    if (projectResponse.ok) setProjects((await projectResponse.json()).projects ?? []);
    if (statsResponse.ok) setStats((await statsResponse.json()));
    if (deploymentResponse.ok) setDeployments((await deploymentResponse.json()).deployments ?? []);
    if (keyResponse.ok) setKeys((await keyResponse.json()).keys ?? []);
  }

  function notify(message: string) { setToast(message); window.setTimeout(() => setToast(null), 3000); }
  async function authenticate(email: string, password: string) {
    if (authBusy) return;
    setAuthBusy(true);
    const client = getSupabaseBrowserClient();
    if (!client) { notify("Supabase is not configured in this deployment. Add the environment variables in Vercel, then redeploy."); setAuthBusy(false); return; }
    const result = authMode === "signup" ? await client.auth.signUp({ email, password, options: { emailRedirectTo: `${window.location.origin}/` } }) : await client.auth.signInWithPassword({ email, password });
    setAuthBusy(false);
    if (result.error) return notify(result.error.message);
    if (!result.data.session) return notify("Account created. Check your email to confirm your address, then log in.");
    setScreen("dashboard"); setUserEmail(email); setUserLabel(email.split("@")[0] || "new user"); await loadAll();
  }
  async function createProject() { if (!newName.trim()) return notify("Project name is required."); const response = await fetch("/api/projects", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: newName, description: newDescription, sourceCode: newSource }) }); const result = await response.json(); if (!response.ok) return notify(result.error ?? "Could not create project."); setModal(null); setNewName(""); setNewDescription(""); setNewSource(""); setProjects((items) => [result.project, ...items]); setTab("projects"); notify("Project created."); }
  async function createDeployment() { if (!project || !deploymentLabel.trim()) return notify("Choose a project and name the deployment."); const response = await fetch("/api/deployments", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ projectId: project.id, label: deploymentLabel, endpoint: deploymentEndpoint }) }); const result = await response.json(); if (!response.ok) return notify(result.error ?? "Could not create deployment."); setDeployments((items) => [result.deployment, ...items]); setModal(null); setDeploymentLabel(""); setDeploymentEndpoint(""); notify("Deployment recorded."); }
  async function protect() { if (!project || !source.trim()) return notify("Choose a project and paste Lua or Luau source first."); setProtecting(true); const response = await fetch("/api/protect", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ projectId: project.id, source, method, options: { minify_output: true, byte_encrypt_all_constants: true, target_lua_version: "5.3" } }) }); const result = await response.json(); setProtecting(false); if (!response.ok) return notify(result.error ?? "Obfuscation failed."); setSource(result.protectedCode); await loadAll(); notify("Obfuscation completed by mopsfl."); }
  async function removeProject(id: string) { if (!window.confirm("Delete this project and its protection history?")) return; const response = await fetch("/api/projects", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id }) }); if (response.ok) { setProjects((items) => items.filter((item) => item.id !== id)); if (project?.id === id) setProject(null); notify("Project deleted."); } }
  async function createKey() { if (!newKeyName.trim()) return notify("Name the API key first."); const response = await fetch("/api/keys", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: newKeyName }) }); const result = await response.json(); if (!response.ok) return notify(result.error ?? "Could not create API key."); setKeys((items) => [result.key, ...items]); setGeneratedKey(result.secret); setNewKeyName(""); notify("Copy the secret now; it will not be shown again."); }
  async function deleteKey(id: string) { const response = await fetch("/api/keys", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id }) }); if (response.ok) setKeys((items) => items.filter((item) => item.id !== id)); }
  async function signOut() { await getSupabaseBrowserClient()?.auth.signOut(); setScreen("landing"); setUserEmail(""); setProjects([]); }

  if (screen === "landing") return <LandingPage onLogin={() => { setAuthMode("login"); setScreen("auth"); }} onSignup={() => { setAuthMode("signup"); setScreen("auth"); }} />;
  if (screen === "auth") return <AuthPage mode={authMode} onBack={() => setScreen("landing")} onModeChange={setAuthMode} onSubmit={authenticate} busy={authBusy} />;
  const filtered = projects.filter((item) => `${item.name} ${item.description}`.toLowerCase().includes(query.toLowerCase()));
  return <><Dashboard userLabel={userLabel} userEmail={userEmail} isOwner={userEmail.toLowerCase() === OWNER_EMAIL} tab={tab} setTab={setTab} projects={projects} filtered={filtered} deployments={deployments} keys={keys} stats={stats} project={project} setProject={(item) => { setProject(item); setSource(item?.source_code ?? ""); }} source={source} setSource={setSource} method={method} setMethod={setMethod} protecting={protecting} onProtect={protect} query={query} setQuery={setQuery} onNewProject={() => setModal("new-project")} onDeleteProject={removeProject} onNewDeployment={() => setModal("new-deployment")} deploymentLabel={deploymentLabel} setDeploymentLabel={setDeploymentLabel} deploymentEndpoint={deploymentEndpoint} setDeploymentEndpoint={setDeploymentEndpoint} onCreateDeployment={createDeployment} newKeyName={newKeyName} setNewKeyName={setNewKeyName} onCreateKey={createKey} onDeleteKey={deleteKey} generatedKey={generatedKey} setGeneratedKey={setGeneratedKey} onSignOut={signOut} toast={toast} />{modal ? <Modal type={modal} projects={projects} project={project} setProject={(item) => { setProject(item); setSource(item?.source_code ?? ""); }} name={newName} setName={setNewName} description={newDescription} setDescription={setNewDescription} source={newSource} setSource={setNewSource} label={deploymentLabel} setLabel={setDeploymentLabel} endpoint={deploymentEndpoint} setEndpoint={setDeploymentEndpoint} onCreateProject={createProject} onCreateDeployment={createDeployment} onClose={() => setModal(null)} /> : null}</>;
}

function LandingPage({ onLogin, onSignup }: { onLogin: () => void; onSignup: () => void }) { return <main className="landing-page jnkie-inspired-page"><nav className="jnkie-nav"><button className="jnkie-brand" onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}><span className="jnkie-brand-mark"><LockKeyhole size={16} /></span><span className="jnkie-brand-name"><strong>Lua</strong>Lock</span></button><div className="jnkie-nav-actions"><button className="jnkie-nav-link" onClick={() => window.open("https://docs.mopsfl.de/", "_blank")}>Docs</button><button className="jnkie-nav-link" onClick={onLogin}>Login</button><button className="jnkie-nav-cta" onClick={onSignup}>Get Started <ArrowRight size={14} /></button></div></nav><section className="jnkie-hero"><div className="jnkie-orb jnkie-orb-left" /><div className="jnkie-orb jnkie-orb-right" /><div className="jnkie-badge"><span /> PRODUCTION-READY</div><h1>Enterprise Script<br /><span>Protection Platform</span></h1><p>Protect, distribute, and control your Lua and Luau scripts with confidence.</p><div className="jnkie-hero-actions"><button className="jnkie-primary-button" onClick={onSignup}>Get started <ArrowRight size={16} /></button><button className="jnkie-secondary-button" onClick={onLogin}>Sign In</button></div><div className="jnkie-proof-row"><span><Check size={13} /> No credit card</span><span><Check size={13} /> Free to start</span><span><Check size={13} /> 5 min setup</span></div></section></main>; }

function AuthPage({ mode, onBack, onModeChange, onSubmit, busy }: { mode: AuthMode; onBack: () => void; onModeChange: (mode: AuthMode) => void; onSubmit: (email: string, password: string) => void; busy: boolean }) { return <main className="auth-page"><nav className="auth-nav"><button className="brand auth-brand" onClick={onBack}><span className="brand-mark"><LockKeyhole size={15} /></span><span>LuaLock</span></button><button className="back-link" onClick={onBack}><ChevronRight size={14} className="back-arrow" /> Back to home</button></nav><div className="auth-layout"><div className="auth-rail"><div className="section-kicker">PRIVATE WORKSPACE</div><h1>{mode === "signup" ? "Your scripts,\nunder lock." : "Welcome\nback."}</h1><p>{mode === "signup" ? "Create a workspace for protected releases, deployments, and API access." : "Pick up where you left off."}</p></div><form className="auth-card" onSubmit={(event) => { event.preventDefault(); const form = event.currentTarget; onSubmit((form.elements.namedItem("email") as HTMLInputElement).value, (form.elements.namedItem("password") as HTMLInputElement).value); }}><div className="auth-card-head"><div className="modal-icon"><LockKeyhole size={17} /></div><div><h2>{mode === "signup" ? "Create your account" : "Log in to LuaLock"}</h2><p>Supabase Auth protects your workspace.</p></div></div><label>Email address<input name="email" required type="email" placeholder="you@example.com" /></label><label>Password<input name="password" required minLength={8} type="password" placeholder="At least 8 characters" /></label><button className="landing-cta auth-submit" type="submit" disabled={busy}>{busy ? "Connecting…" : mode === "signup" ? "Create workspace" : "Log in"} <ArrowRight size={15} /></button><div className="auth-switch">{mode === "signup" ? "Already have an account?" : "New to LuaLock?"} <button type="button" onClick={() => onModeChange(mode === "signup" ? "login" : "signup")}>{mode === "signup" ? "Log in" : "Create an account"}</button></div></form></div></main>; }

function Dashboard(props: { userLabel: string; userEmail: string; isOwner: boolean; tab: Tab; setTab: (tab: Tab) => void; projects: Project[]; filtered: Project[]; deployments: Deployment[]; keys: ApiKey[]; stats: { totalProjects: number; protectedBuilds: number; apiRequests: number; avgProtectionTime: string }; project: Project | null; setProject: (project: Project | null) => void; source: string; setSource: (value: string) => void; method: string; setMethod: (value: string) => void; protecting: boolean; onProtect: () => void; query: string; setQuery: (value: string) => void; onNewProject: () => void; onNewDeployment: () => void; onDeleteProject: (id: string) => void; deploymentLabel: string; setDeploymentLabel: (value: string) => void; deploymentEndpoint: string; setDeploymentEndpoint: (value: string) => void; onCreateDeployment: () => void; newKeyName: string; setNewKeyName: (value: string) => void; onCreateKey: () => void; onDeleteKey: (id: string) => void; generatedKey: string | null; setGeneratedKey: (value: string | null) => void; onSignOut: () => void; toast: string | null }) {
  const { tab, setTab, projects, filtered, deployments, keys, stats, project, setProject, source, setSource, method, protecting, onProtect, query, setQuery, onNewProject, onNewDeployment, onDeleteProject, newKeyName, setNewKeyName, onCreateKey, onDeleteKey, generatedKey, setGeneratedKey, onSignOut, toast } = props;
  return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><LockKeyhole size={15} /></span><span>LuaLock</span><span className="brand-pro">PRO</span></div><div className="workspace-label">WORKSPACE</div><nav className="side-nav">{(Object.keys(tabMeta) as Tab[]).filter((item) => item !== "owner" || props.isOwner).map((item) => { const meta = tabMeta[item]; const Icon = meta.icon; return <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}><Icon size={15} /><span>{meta.label}</span>{item === "projects" ? <span className="nav-count">{projects.length}</span> : null}</button>; })}</nav><div className="side-spacer" /><button className="user-card" onClick={() => setTab("settings")}><span className="avatar">{props.userLabel.slice(0, 1).toUpperCase()}</span><span><strong>{props.userLabel}</strong><small>{props.isOwner ? "Owner account" : "Workspace member"}</small></span><MoreHorizontal size={15} /></button><button className="signout-button" onClick={onSignOut}><LogOut size={14} /> Sign out</button></aside><section className="main-content"><header className="topbar"><div className="breadcrumbs"><span>Workspace</span><ChevronRight size={12} /><strong>{tabMeta[tab].label}</strong></div><div className="topbar-actions"><span className="status-dot" /> Connected <button className="topbar-icon" onClick={() => setTab("settings")}><Settings size={15} /></button></div></header><div className="content-wrap">{tab === "overview" ? <Overview stats={stats} projects={projects} setTab={setTab} onNewProject={onNewProject} /> : null}{tab === "projects" ? <ProjectsPage projects={filtered} query={query} setQuery={setQuery} onNew={onNewProject} onSelect={setProject} onDelete={onDeleteProject} onProtect={(item) => { setProject(item); setTab("obfuscate"); }} /> : null}{tab === "obfuscate" ? <ObfuscatePage projects={projects} project={project} setProject={setProject} source={source} setSource={setSource} method={method} setMethod={props.setMethod} protecting={protecting} onProtect={onProtect} /> : null}{tab === "deployments" ? <DeploymentsPage projects={projects} deployments={deployments} onNew={onNewDeployment} /> : null}{tab === "api" ? <ApiPage keys={keys} name={newKeyName} setName={setNewKeyName} onCreate={onCreateKey} onDelete={onDeleteKey} generatedKey={generatedKey} setGeneratedKey={setGeneratedKey} /> : null}{tab === "settings" ? <SettingsPage userLabel={props.userLabel} userEmail={props.userEmail} onSignOut={onSignOut} /> : null}{tab === "owner" && props.isOwner ? <OwnerPage userEmail={props.userEmail} /> : null}</div>{toast ? <div className="toast"><Check size={15} /> {toast}</div> : null}</section></main>;
}

function Overview({ stats, projects, setTab, onNewProject }: { stats: { totalProjects: number; protectedBuilds: number; apiRequests: number; avgProtectionTime: string }; projects: Project[]; setTab: (tab: Tab) => void; onNewProject: () => void }) { return <div><PageHeading eyebrow="LUA PROTECTION PLATFORM" title="Welcome back" subtitle="A live view of your protected releases and workspace activity." action={<button className="primary-button" onClick={onNewProject}><Plus size={14} /> New project</button>} /><section className="stats-grid"><Stat icon={FolderOpen} label="TOTAL PROJECTS" value={String(stats.totalProjects)} note="" /><Stat icon={ShieldCheck} label="PROTECTED BUILDS" value={String(stats.protectedBuilds)} note="" /><Stat icon={Zap} label="API REQUESTS" value={String(stats.apiRequests)} note="" /><Stat icon={Gauge} label="AVG. PROTECTION TIME" value={stats.avgProtectionTime || "—"} note="" /></section><div className="overview-grid"><section className="panel activity-panel"><div className="panel-head"><div><span className="section-kicker">RECENT ACTIVITY</span><h2>Protection activity</h2></div><button className="text-button" onClick={() => setTab("obfuscate")}>Run protection <ArrowRight size={14} /></button></div><EmptyState title="No protection activity yet" text="Run your first obfuscation job to see real activity here." action="Open obfuscator" onClick={() => setTab("obfuscate")} /></section><section className="panel quick-panel"><div className="panel-head"><div><span className="section-kicker">WORKSPACE</span><h2>Quick actions</h2></div></div><QuickAction icon={Plus} title="Create a project" description="Start a new script workspace" onClick={onNewProject} /><QuickAction icon={ShieldCheck} title="Obfuscate a script" description="Send source to mopsfl" onClick={() => setTab("obfuscate")} /><QuickAction icon={KeyRound} title="Create an API key" description="Connect an external client" onClick={() => setTab("api")} /></section></div><section className="panel"><div className="panel-head"><div><span className="section-kicker">PROJECTS</span><h2>Your projects</h2></div><button className="text-button" onClick={() => setTab("projects")}>View all <ArrowRight size={14} /></button></div>{projects.length ? <div className="project-list">{projects.slice(0, 4).map((item) => <ProjectLine key={item.id} project={item} />)}</div> : <EmptyState title="No projects yet" text="Create a project to store source code, protected output, and deployment history." action="Create your first project" onClick={onNewProject} />}</section></div>; }

function ProjectsPage({ projects, query, setQuery, onNew, onSelect, onDelete, onProtect }: { projects: Project[]; query: string; setQuery: (value: string) => void; onNew: () => void; onSelect: (project: Project) => void; onDelete: (id: string) => void; onProtect: (project: Project) => void }) { return <div><PageHeading eyebrow="WORKSPACE" title="Projects" subtitle="Source, protected output, and status for every script." action={<button className="primary-button" onClick={onNew}><Plus size={14} /> New project</button>} /><div className="toolbar"><div className="search-box"><Search size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search projects" /></div><span className="muted">{projects.length} project{projects.length === 1 ? "" : "s"}</span></div><section className="panel"><div className="project-list">{projects.length ? projects.map((item) => <div className="project-line project-line-actions" key={item.id}><ProjectLine project={item} /><div className="line-actions"><button className="small-button" onClick={() => onProtect(item)}><ShieldCheck size={13} /> Obfuscate</button><button className="small-button" onClick={() => onSelect(item)}>Open</button><button className="danger-icon" aria-label={`Delete ${item.name}`} onClick={() => onDelete(item.id)}><Trash2 size={14} /></button></div></div>) : <EmptyState title={query ? "No matches" : "No projects yet"} text={query ? "Try a different search." : "Projects are saved here after you create them."} action={query ? "Clear search" : "Create a project"} onClick={() => query ? setQuery("") : onNew()} />}</div></section></div>; }

function ObfuscatePage({ projects, project, setProject, source, setSource, method, setMethod, protecting, onProtect }: { projects: Project[]; project: Project | null; setProject: (project: Project | null) => void; source: string; setSource: (value: string) => void; method: string; setMethod: (value: string) => void; protecting: boolean; onProtect: () => void }) { return <div><PageHeading eyebrow="MOPSFL ENGINE" title="Obfuscate" subtitle="Run a real protection job against a saved Lua or Luau project." /><section className="obfuscator-grid"><div className="panel editor-panel"><div className="panel-head"><div><span className="section-kicker">INPUT</span><h2>Source code</h2></div><label className="select-label">Project<select value={project?.id ?? ""} onChange={(event) => setProject(projects.find((item) => item.id === event.target.value) ?? null)}><option value="">Select a project</option>{projects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div><textarea className="code-editor" value={source} onChange={(event) => setSource(event.target.value)} placeholder="Paste Lua or Luau source here..." spellCheck={false} /><div className="editor-footer"><span>{source.length} characters</span><button className="small-button" onClick={() => setSource("")}><X size={13} /> Clear</button></div></div><div className="panel options-panel"><div className="panel-head"><div><span className="section-kicker">CONFIGURATION</span><h2>Protection method</h2></div></div><label className="field-label">Method<select value={method} onChange={(event) => setMethod(event.target.value)}><option value="bytestrings">bytestrings</option><option value="bytestrings,transformnums,minify">bytestrings + transformnums + minify</option><option value="minify">minify</option></select></label><div className="option-note"><ShieldCheck size={16} /><span><strong>mopsfl public API</strong><small>Output is returned from the documented uglifier endpoint. LuaLock does not fake a successful build.</small></span></div><button className="primary-button wide-button" onClick={onProtect} disabled={protecting || !project}>{protecting ? "Obfuscating…" : "Obfuscate script"} <ArrowRight size={14} /></button></div></section><section className="panel output-panel"><div className="panel-head"><div><span className="section-kicker">OUTPUT</span><h2>Protected code</h2></div>{source && project?.protected_code ? <button className="small-button" onClick={() => navigator.clipboard?.writeText(project.protected_code ?? "")}><Copy size={13} /> Copy</button> : null}</div>{project?.protected_code ? <pre className="code-output">{project.protected_code}</pre> : <EmptyState title="No protected output" text="Choose a project, paste source, and run obfuscation. The saved result will appear here." />}</section></div>; }

function DeploymentsPage({ projects, deployments, onNew }: { projects: Project[]; deployments: Deployment[]; onNew: () => void }) { return <div><PageHeading eyebrow="RELEASES" title="Deployments" subtitle="Keep track of where protected projects are released." action={<button className="primary-button" onClick={onNew}><Plus size={14} /> New deployment</button>} /><section className="panel"><div className="panel-head"><div><span className="section-kicker">DEPLOYMENT HISTORY</span><h2>{deployments.length ? "Your deployments" : "No deployments"}</h2></div></div>{deployments.length ? <div className="table-list">{deployments.map((item) => <div className="table-row" key={item.id}><span className="file-icon violet"><GitBranch size={15} /></span><span><strong>{item.label}</strong><small>{projects.find((project) => project.id === item.project_id)?.name ?? "Project"} · {item.endpoint || "No endpoint recorded"}</small></span><span className="badge"><span className="badge-dot" />{item.status}</span><time>{new Date(item.created_at).toLocaleDateString()}</time></div>)}</div> : <EmptyState title="No deployments yet" text="Create one after protecting a project. LuaLock stores the release metadata in Supabase." action="Create deployment" onClick={onNew} />}</section></div>; }

function ApiPage({ keys, name, setName, onCreate, onDelete, generatedKey, setGeneratedKey }: { keys: ApiKey[]; name: string; setName: (value: string) => void; onCreate: () => void; onDelete: (id: string) => void; generatedKey: string | null; setGeneratedKey: (value: string | null) => void }) { return <div><PageHeading eyebrow="INTEGRATIONS" title="API access" subtitle="Create hashed API credentials for your own clients." /><section className="panel api-create"><div><span className="section-kicker">NEW KEY</span><h2>Create an API key</h2><p className="muted">Only the prefix is saved. The full secret is shown once.</p></div><div className="inline-form"><input value={name} onChange={(event) => setName(event.target.value)} placeholder="Key name" /><button className="primary-button" onClick={onCreate}><Plus size={14} /> Create key</button></div></section>{generatedKey ? <section className="secret-banner"><div><strong>Copy your new secret</strong><p>{generatedKey}</p></div><button className="small-button" onClick={() => navigator.clipboard?.writeText(generatedKey)}><Copy size={13} /> Copy</button><button className="danger-icon" onClick={() => setGeneratedKey(null)}><X size={14} /></button></section> : null}<section className="panel"><div className="panel-head"><div><span className="section-kicker">ACTIVE CREDENTIALS</span><h2>{keys.length ? "Your API keys" : "No API keys"}</h2></div></div>{keys.length ? <div className="table-list">{keys.map((item) => <div className="table-row" key={item.id}><span className="file-icon cyan"><KeyRound size={15} /></span><span><strong>{item.name}</strong><small>{item.key_prefix} · created {new Date(item.created_at).toLocaleDateString()}</small></span><button className="danger-icon" onClick={() => onDelete(item.id)}><Trash2 size={14} /></button></div>)}</div> : <EmptyState title="No API keys yet" text="Create one when you are ready to call LuaLock from another service." />}</section></div>; }

function SettingsPage({ userLabel, userEmail, onSignOut }: { userLabel: string; userEmail: string; onSignOut: () => void }) { return <div><PageHeading eyebrow="WORKSPACE" title="Settings" subtitle="Account controls and connection status." /><section className="panel settings-panel"><div className="settings-row"><span className="avatar large">{userLabel.slice(0, 1).toUpperCase()}</span><span><strong>{userLabel}</strong><small>{userEmail} · Authenticated with Supabase Auth</small></span></div><div className="settings-row"><span className="file-icon green"><ShieldCheck size={15} /></span><span><strong>Data ownership</strong><small>Projects, jobs, deployments, and keys are scoped by owner_id with row-level security.</small></span></div><button className="danger-button" onClick={onSignOut}><LogOut size={14} /> Sign out</button></section></div>; }

function OwnerPage({ userEmail }: { userEmail: string }) { return <div><PageHeading eyebrow="OWNER CONSOLE" title="Owner controls" subtitle="Restricted to the LuaLock owner account." /><section className="panel owner-panel"><div className="owner-banner"><span className="file-icon violet"><LockKeyhole size={16} /></span><span><strong>Owner access enabled</strong><small>{userEmail}</small></span></div><div className="owner-grid"><div><strong>Account policy</strong><p>Owner tabs are visible only when the authenticated email matches the configured owner address.</p></div><div><strong>Workspace security</strong><p>All project, API, deployment, and protection routes still require Supabase authentication and row-level security.</p></div></div></section></div>; }

function Modal({ type, projects, project, setProject, name, setName, description, setDescription, source, setSource, label, setLabel, endpoint, setEndpoint, onCreateProject, onCreateDeployment, onClose }: { type: "new-project" | "new-deployment"; projects: Project[]; project: Project | null; setProject: (project: Project | null) => void; name: string; setName: (value: string) => void; description: string; setDescription: (value: string) => void; source: string; setSource: (value: string) => void; label: string; setLabel: (value: string) => void; endpoint: string; setEndpoint: (value: string) => void; onCreateProject: () => void; onCreateDeployment: () => void; onClose: () => void }) { return <div className="modal-backdrop" onMouseDown={(event) => { if (event.currentTarget === event.target) onClose(); }}><section className="modal-card"><div className="modal-head"><div><span className="section-kicker">{type === "new-project" ? "NEW WORKSPACE" : "NEW RELEASE"}</span><h2>{type === "new-project" ? "Create a project" : "Create a deployment"}</h2></div><button className="danger-icon" onClick={onClose}><X size={16} /></button></div>{type === "new-project" ? <><label className="field-label">Name<input value={name} onChange={(event) => setName(event.target.value)} placeholder="my-script" /></label><label className="field-label">Description<input value={description} onChange={(event) => setDescription(event.target.value)} placeholder="What does this script do?" /></label><label className="field-label">Source code<textarea className="modal-code" value={source} onChange={(event) => setSource(event.target.value)} placeholder="Optional Lua or Luau source" spellCheck={false} /></label><button className="primary-button wide-button" onClick={onCreateProject}>Create project <ArrowRight size={14} /></button></> : <><label className="field-label">Project<select value={project?.id ?? ""} onChange={(event) => setProject(projects.find((item) => item.id === event.target.value) ?? null)}><option value="">Choose a project</option>{projects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="field-label">Deployment name<input value={label} onChange={(event) => setLabel(event.target.value)} placeholder="production" /></label><label className="field-label">Endpoint (optional)<input value={endpoint} onChange={(event) => setEndpoint(event.target.value)} placeholder="https://..." /></label><button className="primary-button wide-button" onClick={onCreateDeployment}>Create deployment <ArrowRight size={14} /></button></>}</section></div>; }

function PageHeading({ eyebrow, title, subtitle, action }: { eyebrow: string; title: string; subtitle: string; action?: React.ReactNode }) { return <header className="page-heading"><div><div className="section-kicker"><span className="pulse" /> {eyebrow}</div><h1>{title}</h1><p>{subtitle}</p></div>{action}</header>; }
function Stat({ icon: Icon, label, value, note }: { icon: typeof Gauge; label: string; value: string; note: string }) { return <div className="stat-card"><span className="stat-icon"><Icon size={16} /></span><span><small>{label}</small><strong>{value}</strong>{note ? <em>{note}</em> : null}</span></div>; }
function ProjectLine({ project }: { project: Project }) { const Icon = project.language === "Luau" ? FileCode2 : Code2; return <div className="project-line"><span className="file-icon green"><Icon size={15} /></span><span><strong>{project.name}</strong><small>{project.description || "No description"}</small></span><span className="language">{project.language}</span><span className={`badge ${project.status === "Draft" ? "badge-gray" : ""}`}><span className="badge-dot" />{project.status}</span></div>; }
function QuickAction({ icon: Icon, title, description, onClick }: { icon: typeof Gauge; title: string; description: string; onClick: () => void }) { return <button className="quick-action" onClick={onClick}><span className="quick-icon"><Icon size={15} /></span><span><strong>{title}</strong><small>{description}</small></span><ChevronRight size={14} /></button>; }
function EmptyState({ title, text, action, onClick }: { title: string; text: string; action?: string; onClick?: () => void }) { return <div className="empty-state"><span className="empty-icon"><Terminal size={17} /></span><h3>{title}</h3><p>{text}</p>{action && onClick ? <button className="small-button" onClick={onClick}>{action} <ArrowRight size={13} /></button> : null}</div>; }
